[[section-solution-strategy]]
== Solution Strategy

=== Technology decisions

We are using the following technologies for the development of the application:

- Solid. Specification that lets people store their data securely in decentralized data stores called Pods. This was a constraint.
- React. A open-source JavaScript library for building user interfaces. We use it since it is easy to lern, its high performance and the high demand of this technology.

=== Decisions about the top-level decomposition of the system

* We are starting this project from the public template Arquisoft/lomap_0

=== Decisions on how to achieve key quality goals

|===
|Quality goal|Approach
|Security and Privacy| SOLID pods will be used to store the user data securely in a decentralized way.
|Responsiveness|React will be used for achieving a responsiveness web application.
|Maintanability|The code will be clean, avoiding bad smells.
|Scalability|The project has to be easy to interact with, in order to be easy to add functionality (i.e.: the optional requirements)
|===


=== Relevant organizational decisions

- *Language*: As said before, the prefered language for contributions to the project is set to be english as we intend that this project can reach the more people the better.

- *Issues*: Although being just two people enables quick and instant comunication thorugh different tools, we have to try to reflect the actual issues of the project in the repository.

- *GitHub Projects*: We intend to use the GitHub project to organize the work that is to be done, has been done or is being done. 
