name: CI for LOMAP_ES1b33

on:
  pull_request:
    branches: 
      - master
  push:
    branches: 
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: webapp
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm ci
    - run: npm test --coverage --watchAll
    - name: Analyze with SonarCloud
      uses: sonarsource/sonarcloud-github-action@master
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  docker-push-webapp:
    name: Push webapp Docker Image to GitHub Packages
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
    - uses: actions/checkout@v3
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      env:
        DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
        API_KEY_GOOGLE_MAPS: ${{ secrets.API_KEY_GOOGLE_MAPS }}
        CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
        CLOUDINARY_PRESET: ${{ secrets.CLOUDINARY_PRESET }}
        CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
        CLOUDINARY_API_API_SECRET: ${{ secrets.CLOUDINARY_API_API_SECRET }}
        HTTPS_PRIVATEKEY: ${{ secrets.HTTPS_PRIVATEKEY }}
        HTTPS_CERTIFICATE: ${{ secrets.HTTPS_CERTIFICATE }}
      with:
          name: pelotazos123/lomap_es1b33/webapp
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PUSH_TOKEN }}
          registry: ghcr.io
          workdir: webapp
          buildargs: DEPLOY_HOST, API_KEY_GOOGLE_MAPS, CLOUDINARY_CLOUD_NAME, CLOUDINARY_PRESET, CLOUDINARY_API_KEY, CLOUDINARY_API_API_SECRET,HTTPS_PRIVATEKEY, HTTPS_CERTIFICATE
  deploy:
    name: Deploy over SSH
    runs-on: ubuntu-latest
    needs: [docker-push-webapp]
    steps:
    - name: Deploy over SSH
      uses: fifsky/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        user: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        command: |
          wget https://raw.githubusercontent.com/pelotazos123/lomap_es1b33/master/docker-compose-deploy.yml -O docker-compose.yml
          docker-compose stop
          docker-compose rm -f
          docker-compose pull   
          docker-compose up -d
